trigger:
  branches:
    include:
      - main

pool:
  name: Default

variables:
  SB3_FILE: 'AnshuAbhi-Game.sb3'
  BUILD_DIR: 'site'

steps:
# 1. Change directory explicitly to Sources Directory
- script: |
    pushd "$(Build.SourcesDirectory)"
    echo "Current working directory: %CD%"
  displayName: 'cd to sources'

# 2. Verify the Scratch file exists
- script: |
    echo "Verifying existence of %SB3_FILE%"
    if not exist "%SB3_FILE%" (
      echo "ERROR: %SB3_FILE% missing!"
      exit /b 1
    )
    echo "%SB3_FILE% found."
  displayName: 'Verify .sb3 exists'

# 3. Initialize npm and package Scratch project into ZIP in source directory
- script: |
    npm init -y >nul 2>&1
    npm install @turbowarp/packager --no-save
    npx turbopackager "%SB3_FILE%" --target html --output "$(Build.SourcesDirectory)\site.zip"
    if not exist "$(Build.SourcesDirectory)\site.zip" (
      echo "ERROR: site.zip was not created"
      dir "$(Build.SourcesDirectory)"
      exit /b 1
    )
    echo "site.zip successfully created at $(Build.SourcesDirectory)\site.zip"
  displayName: 'Package Scratch to HTML'

# 4. Extract the ZIP file from the same exact path
- task: ExtractFiles@1
  inputs:
    archiveFilePatterns: '$(Build.SourcesDirectory)\site.zip'
    destinationFolder: '$(Build.ArtifactStagingDirectory)\$(BUILD_DIR)'
    cleanDestinationFolder: true
  displayName: 'Extract site.zip'

# 5. Verify extraction by checking index.html exists
- script: |
    if exist "$(Build.ArtifactStagingDirectory)\$(BUILD_DIR)\index.html" (
      echo "Extraction verified: index.html found."
    ) else (
      echo "ERROR: index.html missing after extraction!"
      exit /b 1
    )
  displayName: 'Verify extraction'

# 6. Publish extracted artifact (optional)
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)\$(BUILD_DIR)'
    artifactName: 'site'
  displayName: 'Publish site artifact'

# 7. Deploy to Azure Static Web Apps
- script: |
    npm install @azure/static-web-apps-cli --no-save
    npx swa deploy "$(Build.ArtifactStagingDirectory)\$(BUILD_DIR)" --deployment-token "$(SWA_TOKEN)" --env production --app-name "anshu-abhi-balloongame"
  env:
    SWA_TOKEN: $(SWA_TOKEN)
  displayName: 'Deploy to Azure Static Web Apps'
